### ISSUE TITLE
"SQLSTATE[HY000]: General error: 1364 Field 'post_id' doesn't have a default value (SQL: insert into `steps` (`name`, `body`, `updated_at`, `created_at`) valuesのエラーが出る

### ISSUE THREAD

**Issue by Shun-ichiroTanaka** [Shun-ichiroTanaka/step2#2]
## 対象画面・画面 
新規投稿ページ

## 想定手順  
①タイトル、カテゴリー、目標時間、stepタイトル、step本文をそれぞれ記入し登録する。
②タイトルと目標時間はPostモデルに、
カテゴリーはTagモデルに、
stepタイトルとstep本文はstepモデルにそれぞれ保存される。
③投稿後トップページへリダイレクト

## 実行環境
mac
chrome

## 優先度  
大

## エラー画像
![スクリーンショット 2020-01-05 18 23 19](https://user-images.githubusercontent.com/34049491/71777794-834cfb80-2fe8-11ea-9d20-020da89ca5a9.png)

**Comment by Shun-ichiroTanaka** [comment]
## エラー原因推定
postとstepsは1対多の関係で、
例えば5つあるsteps情報を全て取り出したい場合、
step_idを一つ一つ取り出すのではなくpostモデルから
$post->step->nameのように取り出す

stepモデル自体の投稿送信情報はid, name, bodyなので
外部キー接続でpost_idをPostモデルからデフォルトで指定しておかなければならないが
今回はそれがうまくいっていないのではないか。＝モデルの設定がおかしい？

![スクリーンショット 2020-01-05 18 38 39](https://user-images.githubusercontent.com/34049491/71777957-a37dba00-2fea-11ea-8b6d-4e88a3e64bc1.png)

**Comment by kakipo** [comment]
エラーメッセージ自体は steps の新しいレコードを INSERT する際に `post_id` が指定されていないことに起因するもののようですね！

## 要確認1

`belongsToMany` はどのような関係のときに用いられるリレーションでしょうか。

https://github.com/Shun-ichiroTanaka/step2/blob/c76b9e03c01713c352ba2aac488a1220fada79cd/app/Step.php#L19

## 要確認2

このループに入る前に `$request` はどのような値になっていますか？
また、ループの中で `$key` `$value` はどのような値になっていますか？

https://github.com/Shun-ichiroTanaka/step2/blob/15d8de13be181f0ec623210d6544320d15ccc889/app/Http/Controllers/PostController.php#L49

**Comment by Shun-ichiroTanaka** [comment]
## 確認結果①
`belongsToMany`は多対多のリレーションで使用するものでした。
https://readouble.com/laravel/5.8/ja/eloquent-relationships.html

したがって`belongsToMany`を`belongsTo`に変更しました。

**Comment by Shun-ichiroTanaka** [comment]
# 確認結果②
> ## 要確認2
> このループに入る前に `$request` はどのような値になっていますか？
> また、ループの中で `$key` `$value` はどのような値になっていますか？
> 
> https://github.com/Shun-ichiroTanaka/step2/blob/15d8de13be181f0ec623210d6544320d15ccc889/app/Http/Controllers/PostController.php#L49

要確認①は直してうまく挙動できなかったので要確認②の問題と判断。
配列の登録の処理がうまくできていないのが原因と推定される。
このissueを閉じ新しいissueを作成します。

**Comment by Shun-ichiroTanaka** [comment]
## エラーの原因
・stepという投稿の本文部分を登録
①step(nameとbody)をaddボタンで追加
②複数のstepsを保存

・タグ(カテゴリー)の登録

**Comment by kakipo** [comment]
一旦 tag は置いておいて、steps の保存ができることを目指しましょっか！

> 確認結果①

いいですね :+1: 

> ・tagsとstepsは送信に失敗している
`$request` を見る限り、サーバー（Controller）までは情報を送れているように見えますが、何に失敗しているんでしょ...？

> 確認結果②

> ②$keyにはstepの内容が入ってくる
> ③$valueにはstepsの内容が入ってくる

ここがまだちょっと見えていないですね。
例えばループの中で `echo` を使うなどして `$key` や `$value` の中身がそれぞれどう変化するか確認できますか？

**Comment by Shun-ichiroTanaka** [comment]
>例えばループの中で echo を使うなどして $key や $value の中身がそれぞれどう変化するか確認できますか？
↓↓↓
## var_dump()で$keyと$valueの値をそれぞれ確認
①$value
![スクリーンショット 2020-01-07 18 08 48](https://user-images.githubusercontent.com/34049491/71883142-216fcb80-3179-11ea-9b0c-cd6f6ed00124.png)
![スクリーンショット 2020-01-07 18 08 55](https://user-images.githubusercontent.com/34049491/71883177-33516e80-3179-11ea-982d-1a3a37b56737.png)
→stepのnameとbodyが入ってきた

②$key
![スクリーンショット 2020-01-07 18 14 04](https://user-images.githubusercontent.com/34049491/71883304-84616280-3179-11ea-9ad4-8dfaab562a4a.png)
![スクリーンショット 2020-01-07 18 13 47](https://user-images.githubusercontent.com/34049491/71883310-86c3bc80-3179-11ea-9f44-60a3c26fb143.png)
→stepsのidが入ってきた？

**Comment by kakipo** [comment]
なるほど `var_dump` という関数があるのですね。便利ですね。（PHP は疎くて...）
https://online.dhw.co.jp/kuritama/function-tools-be-used-for-debugging-php/

> →stepsのidが入ってきた？

steps はまだ DB に保存されていないので id は採番されていないハズです。
また id は 1 から始まるハズ。この数字は何でしょうか？

...
答えを言うと配列の添字（index）ですね。

こんなイメージです。

![_SQLSTATE_HY000___General_error__1364_Field__post_id__doesn_t_have_a_default_value__SQL__insert_into_`steps`__`name`__`body`__`updated_at`__`created_at`__valuesのエラーが出る_·_Issue__2_·_Shun-ichiroTanaka_step2](https://user-images.githubusercontent.com/2214179/71884019-dfe02000-317a-11ea-9bc1-bb8531a908be.png)

Step の保存には `post_id` `name` `body` の 3 つの項目が必要でした。
このループの中でそれぞれの項目を設定し、保存できるハズです！

**Comment by Shun-ichiroTanaka** [comment]
![スクリーンショット 2020-01-07 19 35 53](https://user-images.githubusercontent.com/34049491/71889215-03a86380-3185-11ea-99b7-45907edbdd3c.png)

**Comment by Shun-ichiroTanaka** [comment]
# 登録処理成功
![スクリーンショット 2020-01-14 16 16 16](https://user-images.githubusercontent.com/34049491/72322287-59cb5880-36e9-11ea-931d-2ffd4a1f2526.png)
