### ISSUE TITLE
記事の更新をすると新しい記事が作られてしまう

### ISSUE THREAD

**Issue by Shun-ichiroTanaka** [Shun-ichiroTanaka/step2#4]
## 対象画面
マイページ

## 想定
編集ボタンから更新したら元の記事を上書きして保存する

## 現在
編集ボタンから更新すると元の記事とは別に新しい記事が追加されてしまう
(更新自体はできている)
## 映像
![画面収録-2020-01-16-14 00 48](https://user-images.githubusercontent.com/34049491/72495057-0f70e580-3869-11ea-9753-f8adab83557d.gif)

## controller
https://github.com/Shun-ichiroTanaka/step2/blob/c8b865c3ede19252156e6a51786ddbb26130faa4/app/Http/Controllers/PostController.php#L132

## view
https://github.com/Shun-ichiroTanaka/step2/blob/master/resources/views/posts/edit.blade.php

**Comment by kakipo** [comment]
`$post = Post::find($id);` この後で `$post` を dump するとどうなりますかね？

**Comment by kakipo** [comment]
コメントテスト

**Comment by Shun-ichiroTanaka** [comment]
$post = Post::find($id);　にはidが入ってきます！
![スクリーンショット 2020-01-16 18 17 04](https://user-images.githubusercontent.com/34049491/72510249-6dfb8b00-388c-11ea-912b-2debd3dbc299.png)

**Comment by kakipo** [comment]
なるほど！クエリは理解しました。

1. 実際に `$post` を dump するとどのような表示になりますか？
2. step の保存箇所をコメントアウトして処理を実行するとどうなりますか？
該当箇所: https://github.com/Shun-ichiroTanaka/step2/blob/c8b865c3ede19252156e6a51786ddbb26130faa4/app/Http/Controllers/PostController.php#L143-L149

**Comment by Shun-ichiroTanaka** [comment]
## var_dumpを実行
![スクリーンショット 2020-01-16 18 34 07](https://user-images.githubusercontent.com/34049491/72511972-dba8b680-388e-11ea-8042-00f4fa48c7cc.png)
↓↓↓↓
![スクリーンショット 2020-01-16 18 35 10](https://user-images.githubusercontent.com/34049491/72512207-f713c180-388e-11ea-9c2f-53448fff4e26.png)
何も出てこない

**Comment by kakipo** [comment]
ブラウザではなく、コンソール上に内容出力されていませんか？

**Comment by kakipo** [comment]
あ、あとリダイレクト部分はコメントアウトしなくて良いです！

**Comment by Shun-ichiroTanaka** [comment]
![スクリーンショット 2020-01-16 18 40 07](https://user-images.githubusercontent.com/34049491/72512792-a6509880-388f-11ea-8d54-9e43fdca4966.png)
![スクリーンショット 2020-01-16 18 38 38](https://user-images.githubusercontent.com/34049491/72512798-a9e41f80-388f-11ea-8cb2-c42adbb9421b.png)

**Comment by kakipo** [comment]
ブラウザのコンソールではなくて、ターミナルか何か、サーバのログなどが流れる場所に dump 内容出力されませんかね...？

**Comment by kakipo** [comment]
（すいません laravel あんま詳しくなくて、とりあえず `$post` の中身がわかれば方法は何でも良いです）

**Comment by Shun-ichiroTanaka** [comment]
![スクリーンショット 2020-01-16 18 50 32](https://user-images.githubusercontent.com/34049491/72514101-65f21a00-3891-11ea-8b2a-ac33f6da5b5f.png)
すみません、、それらしきものが見つからないです。。

**Comment by kakipo** [comment]
む〜。

では

step の保存箇所 *「だけ」* をコメントアウトして処理を実行するとどうなりますか？
該当箇所: https://github.com/Shun-ichiroTanaka/step2/blob/c8b865c3ede19252156e6a51786ddbb26130faa4/app/Http/Controllers/PostController.php#L143-L149

**Comment by kakipo** [comment]
ちなみに `dd()` というデバッグ用のメソッドがあるようです。

https://bsblog.casareal.co.jp/archives/1992

**Comment by Shun-ichiroTanaka** [comment]
$stepをコメントアウトしたものもうまくいきませんでした..
![スクリーンショット 2020-01-16 19 17 59](https://user-images.githubusercontent.com/34049491/72516392-ed8d5800-3894-11ea-95ed-96756240a750.png)


マイページから編集ページにいく際に、
web.phpというルーティングの設定で
![スクリーンショット 2020-01-16 19 14 01](https://user-images.githubusercontent.com/34049491/72516043-604a0380-3894-11ea-830c-0f0635323d03.png)
edit.blade.phpというviewファイルを返します。
この処理はPostControllerのeditというメソッドです。
このときpostモデルとstepモデルの情報を返すようにしています。
edit.blade.phpでpostされた情報を更新するupdateメソッドの中でvar_dumpをしようとしていましたがうまくいっていません。

editメソッドによりviewには$postが届いていてupdateするときにはない？ということでしょうか？？
![スクリーンショット 2020-01-16 19 19 34](https://user-images.githubusercontent.com/34049491/72516528-2af1e580-3895-11ea-9c64-329f3620b3e3.png)
![スクリーンショット 2020-01-16 19 19 28](https://user-images.githubusercontent.com/34049491/72516539-2fb69980-3895-11ea-924f-18cc03bfced8.png)

**Comment by kakipo** [comment]
> $stepをコメントアウトしたものもうまくいきませんでした..

キャプチャでは `$post -> save();` もコメントアウトしているように見えますが意図的ですか...？

`dd()` メソッドを使って `$post` の中身を見れますかね？

**Comment by Shun-ichiroTanaka** [comment]
記事更新で新しい記事が作られてしまうのはviewのeditファイルのformアクションがnewと同じのままだったからでした。したがってアクションをupdateに変更しました(↓)
![スクリーンショット 2020-01-24 15 17 16](https://user-images.githubusercontent.com/34049491/73048481-a4548e00-3ebc-11ea-9765-895f8fdd63d5.png)

**Comment by Shun-ichiroTanaka** [comment]
以下でpostとstepの取得に成功
![スクリーンショット 2020-01-24 22 57 35](https://user-images.githubusercontent.com/34049491/73074422-f4ebdb80-3efc-11ea-8ae7-7b7cfe42695e.png)
![スクリーンショット 2020-01-24 22 57 25](https://user-images.githubusercontent.com/34049491/73074427-f6b59f00-3efc-11ea-90d2-75fb2fc5c71d.png)

**Comment by Shun-ichiroTanaka** [comment]
![スクリーンショット 2020-01-24 23 03 45](https://user-images.githubusercontent.com/34049491/73074815-d33f2400-3efd-11ea-875e-b0eb3c9b699b.png)

しかしpostするとnull objectに
