### ISSUE TITLE
記事の更新でTrying to get property 'steps' of non-objectとなる

### ISSUE THREAD

**Issue by Shun-ichiroTanaka** [Shun-ichiroTanaka/step2#6]
記事の更新ボタンを押すとこのエラーがでる
![スクリーンショット 2020-01-24 23 03 45](https://user-images.githubusercontent.com/34049491/73091781-7f910280-3f1e-11ea-818c-b47672a011ac.png)

**Comment by kakipo** [comment]
`$id` の中身と `Post::find($id)` の中身は何が格納サれていますか？

**Comment by Shun-ichiroTanaka** [comment]
## ①edit($id)の中身
![スクリーンショット 2020-01-26 18 19 09](https://user-images.githubusercontent.com/34049491/73133172-6e540d00-4068-11ea-9fa8-6a8b25223fd4.png)
![スクリーンショット 2020-01-26 18 18 51](https://user-images.githubusercontent.com/34049491/73133173-701dd080-4068-11ea-809f-92ae4a31946c.png)

## ②$post = Post::where('id', $id)->first();の中身
![スクリーンショット 2020-01-26 18 20 08](https://user-images.githubusercontent.com/34049491/73133183-81ff7380-4068-11ea-81bb-7b34c886231e.png)
![スクリーンショット 2020-01-26 18 20 51](https://user-images.githubusercontent.com/34049491/73133191-9a6f8e00-4068-11ea-8785-7749be3e8843.png)

## ③$step = Post::find($id);の中身
![スクリーンショット 2020-01-26 18 22 58](https://user-images.githubusercontent.com/34049491/73133227-fafecb00-4068-11ea-8e8e-64af95e45464.png)

## ④$steps = Post::find($id)->steps;の中身
![スクリーンショット 2020-01-26 18 25 39](https://user-images.githubusercontent.com/34049491/73133247-4e711900-4069-11ea-932e-522f452aa0cd.png)
![スクリーンショット 2020-01-26 18 26 18](https://user-images.githubusercontent.com/34049491/73133256-621c7f80-4069-11ea-85c0-db8bd3f18804.png)
![スクリーンショット 2020-01-26 18 26 27](https://user-images.githubusercontent.com/34049491/73133258-63e64300-4069-11ea-924e-b10cb356fb45.png)

となりました！

**Comment by Shun-ichiroTanaka** [comment]
ルーティングの見直しでこのエラーは解決しました。
新しいエラーが出たのでこちらは閉じます
https://github.com/Shun-ichiroTanaka/step2/blob/3c05a9c33c0fea634f322a26772f3a4caa93e8c8/routes/web.php#L18
